apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: content-store
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: content-store
    spec:
      containers:
      - args:
        - bundle
        - exec
        - unicorn
        - -p
        - "80"
        env:
        - name: GOVUK_APP_DOMAIN
          value: default.svc.cluster.local
        - name: MONGO_WRITE_CONCERN
          value: "1"
        - name: RAILS_ENV
          value: production
        - name: SECRET_KEY_BASE
          value: 875c6bf4c48da9bb41f4cfd25d09bf5e2a62d88b39efc4bd9c498e6c8f61e4df740af87386f97269525e01b5f74402512eb6a4723882579f10aa95f6e2971fc2
        - name: SECRET_TOKEN
          value: 875c6bf4c48da9bb41f4cfd25d09bf5e2a62d88b39efc4bd9c498e6c8f61e4df740af87386f97269525e01b5f74402512eb6a4723882579f10aa95f6e2971fc2
        - name: MONGODB_URI
          value: mongodb://content-store-mongodb/content_store
        - name: GOVUK_WEBSITE_ROOT
          value: http://www.127.0.0.1.nip.io/
        image: govuk/content-store:deployed-to-production
        name: content-store
        ports:
        - containerPort: 80
      restartPolicy: Always
